added www-urlendoded-form support
vramework/vramework pull request #6
Opened 2021-06-24 13:26 UTC by neumark

2021-06-24 14:04 UTC, yasserf commented on lambda/lambda.ts
> +import * as querystring from 'querystring'
is this already a ependency?

2021-06-24 14:09 UTC, yasserf commented on lambda/lambda.ts
> +import * as querystring from 'querystring'
seems like it is missing (explicitly) and works because a dependency of a dependency has it. 

Otherwise this pr looks good! thanks!

2021-06-24 14:10 UTC, yasserf requested changes
requires explicit dependency

2021-06-24 14:21 UTC, neumark commented on lambda/lambda.ts
> +import * as querystring from 'querystring'
nice catch, I thought it was part of the node standard library

2021-06-25 08:45 UTC, neumark commented
I think it's ready now

2021-06-25 10:40 UTC, yasserf approved these changes

2021-06-25 10:40 UTC, merged

2021-06-25 10:41 UTC, yasserf commented
thanks!